### ISSUE TITLE
Swin-Transformer Eager Global 完整训练实验

### ISSUE THREAD

**Issue by Ldpe2G** [Oneflow-Inc/swin-transformer#10]
# eager global 1d sbp 完整训练

- oneflow swin 实验分支  https://github.com/Oneflow-Inc/swin-transformer/pull/9

## 实验1: mixup on + clip-grad on
- dataset: `CIFAR100`
- model: Swin Tiny 28M
- batch size: 32

| Framework | Init Method    | Version   | Epoch| Avg Time for Each Epoch | Acc@1 | Log   |
| --------- | --------------- | ------------------- | ----- |------- | -------- | ----- |
| pytorch   | 固定初始化 | 1.10.1                                 | 300  | ~50s | 78.5%    | [log](https://github.com/Oneflow-Inc/swin-transformer/files/7794992/cifar100_swin_tiny_mixup_on_clip_grad_on.txt) |
| oneflow ddp   | 随机初始化       | master nightly 0.7.0.dev20210119+cu112 | 300  |  ~58s |78.92%  | [log](https://github.com/Oneflow-Inc/swin-transformer/files/7902995/cifar100_swin_tiny_mixup_on_clip_grad_on_new_random_init.log) |
| oneflow eager global1d sbp | 随机初始化       | 基于 profiling_fuse_ddp 分支加上 https://github.com/Oneflow-Inc/oneflow/pull/7225 的修改 | 300  | ~2m50s | 78.35%  | [log](https://github.com/Oneflow-Inc/swin-transformer/files/7902993/earger_consistent_cifar100_swin_tiny_mixup_on_clip_grad_on_new_random_init.log)|

## 实验结论
- 从初步实验结果来看，eager consistent 的精度还算正常，至少没有出现之前 resnet50 训崩的情况
- eager consistent 相比于 ddp，一个epoch要慢约 90秒 左右，需要优化一下

**Comment by yuanms2** [comment]
> 2d sbp 训练过程中发现，每训练几十个epoch之后会卡住然后报错

这个问题不知道后来解决了没有
